version: "3.9"

services:
  api:
    restart: always
    env_file:
      - ./apps/api/.env
    environment:
      ENVIRONMENT: development
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
      target: debug
    ports:
      - 127.0.0.1:3200:80
      - 127.0.0.1:9229:9229
    volumes:
      - ./apps/api/src:/app/src
      - ./apps/api/test:/app/test
    depends_on:
      typesense:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      connector:
        condition: service_healthy
    links:
      - typesense
      - mongodb
    healthcheck:
      test: curl -sf "http://127.0.0.1:80/health"
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5

  frontend:
    restart: always
    environment:
      API_URI: http://api:80
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
      target: debug
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:9230:9229
    volumes:
      - ./apps/frontend/:/app/
      - /app/.next
      - /app/node_modules
    links:
      - api
    depends_on:
      api:
        condition: service_healthy

  connector:
    restart: always
    env_file:
      - ./apps/connector/.env
    environment:
      ENVIRONMENT: development
    build:
      context: ./apps/connector
      dockerfile: Dockerfile.dev
      target: debug
    ports:
      - 127.0.0.1:3201:80
    volumes:
      - ./apps/connector/src:/app/src
    depends_on:
      typesense:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    links:
      - typesense
      - mongodb
    healthcheck:
      test: curl -sf "http://127.0.0.1:80/health"
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5

  typesense:
    build:
      context: ./apps/backend/typesense
      dockerfile: Dockerfile
    healthcheck:
      test: curl -sf "http://127.0.0.1:8108/health"
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5
    env_file:
      - ./apps/backend/typesense/.env
    environment:
      TYPESENSE_DATA_DIR: /typesense/data
    tmpfs:
      - /typesense/data
      - /typesense/logs

  mongodb:
    image: bitnami/mongodb:5.0
    env_file:
      - ./apps/backend/mongodb/primary.env
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_REPLICA_SET_MODE: primary
    ports:
      - 27017:27017
    healthcheck:
      test:
        - CMD
        - mongo
        - --eval
        - db.adminCommand('ping')
