# Install PNPM
FROM bitnami/node:16 as pnpm
WORKDIR /app/
RUN apt-get install curl && curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
COPY pnpm-lock.yaml ./
RUN pnpm fetch
COPY package.json ./

# Install Dependencies
FROM pnpm as deps
WORKDIR /app/
RUN pnpm install -r --offline

# Copy config Files
FROM deps as files
WORKDIR /app/
COPY tsconfig.json ./

# Debug
FROM files as debug
WORKDIR /app/
EXPOSE 3000
EXPOSE 9229
CMD [ "pnpm", "dev" ]
